import { initializeApp } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js";
import { getAuth, setPersistence, browserLocalPersistence, onAuthStateChanged, createUserWithEmailAndPassword, signInWithEmailAndPassword, sendEmailVerification, sendPasswordResetEmail, signOut, reload, updateProfile } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
import { getDatabase, ref, get, set, update, push, onValue, off, onDisconnect, serverTimestamp, runTransaction, goOnline } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-database.js";

const firebaseConfig={apiKey:"AIzaSyCFsAAGRTW0et7_pQnxhLtkGR174kRqikg",authDomain:"arinexservice.firebaseapp.com",databaseURL:"https://arinexservice-default-rtdb.asia-southeast1.firebasedatabase.app",projectId:"arinexservice",storageBucket:"arinexservice.firebasestorage.app",messagingSenderId:"780762123532",appId:"1:780762123532:web:2c3b8a374eba5871490d29",measurementId:"G-SB9MXMZVCF"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getDatabase(app);

// Set persistence before any auth observer is registered.
const persistenceReady = setPersistence(auth,browserLocalPersistence);
const $=id=>document.getElementById(id);
let currentUser=null,myProfile=null,contacts={},activeUid=null,activeChatId=null,contactsUnsub=null,messagesUnsub=null,presenceDisconnect=null,deferredInstallPrompt=null,toastTimer=null,verifyCooldownUntil=0,authBusy=false;
const views={auth:$('authView'),verify:$('verifyView'),chat:$('chatView')};
const normalizeEmail=v=>String(v??'').trim().toLowerCase();
const safeText=(v,max=4000)=>String(v??'').trim().slice(0,max);
const isEmail=v=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(normalizeEmail(v));
const isStrongPassword=v=>/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z0-9]).{8,72}$/.test(v);
function setView(name){Object.values(views).forEach(v=>v.classList.add('hidden'));views[name].classList.remove('hidden')}
function notice(el,msg,type='info'){el.textContent=msg;el.classList.remove('hidden','error');if(type==='error')el.classList.add('error')}
function clearNotice(el){el.classList.add('hidden')}
function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2800)}
function firebaseMessage(e){const c=e?.code||'';const map={'auth/invalid-credential':'Email atau password salah.','auth/invalid-email':'Format email tidak valid.','auth/email-already-in-use':'Email sudah terdaftar.','auth/weak-password':'Password terlalu lemah.','auth/too-many-requests':'Terlalu banyak percobaan. Tunggu beberapa saat.','auth/network-request-failed':'Jaringan bermasalah.','auth/operation-not-allowed':'Email/password belum diaktifkan di Firebase.','auth/unauthorized-continue-uri':'Domain aplikasi belum ada di Authorized domains Firebase.'};return map[c]||e?.message||'Terjadi kesalahan.'}
function switchAuth(panel){$('loginPanel').classList.toggle('hidden',panel!=='login');$('registerPanel').classList.toggle('hidden',panel!=='register');$('resetPanel').classList.toggle('hidden',panel!=='reset');clearNotice($('authNotice'))}
function actionCodeSettings(){return{url:window.location.origin+window.location.pathname,handleCodeInApp:false}}
function chatIdFor(a,b){return[a,b].sort().join('__')}
function formatTime(ts){return new Intl.DateTimeFormat('id-ID',{hour:'2-digit',minute:'2-digit'}).format(new Date(Number(ts)||Date.now()))}
async function sha256Hex(value){const bytes=new TextEncoder().encode(value);const digest=await crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(digest)).map(x=>x.toString(16).padStart(2,'0')).join('')}
async function waitFor(p,ms=15000){let t;const timeout=new Promise((_,rej)=>t=setTimeout(()=>rej(new Error('Koneksi ke Firebase Realtime Database terlalu lama. Periksa koneksi internet, URL database, dan Rules.')),ms));try{return await Promise.race([p,timeout])}finally{clearTimeout(t)}}
async function refreshUser(forceVerified=false){if(!auth.currentUser)throw new Error('Sesi tidak ditemukan.');await reload(auth.currentUser);await auth.currentUser.getIdToken(true);currentUser=auth.currentUser;if(forceVerified&&!currentUser.emailVerified)throw new Error('Email belum terverifikasi.');return currentUser}
function renderMe(){const name=safeText(myProfile?.displayName,40)||safeText(currentUser?.displayName,40)||normalizeEmail(currentUser?.email).split('@')[0]||'Pengguna';const email=currentUser?.email||'';['myName','menuName'].forEach(id=>$(id).textContent=name);['myEmail','menuEmail'].forEach(id=>$(id).textContent=email);return name}
async function ensureProfile(user){await refreshUser(true);const email=normalizeEmail(user.email);const hash=await sha256Hex(email);const uref=ref(db,`users/${user.uid}`),pref=ref(db,`publicProfiles/${user.uid}`),iref=ref(db,`emailIndex/${hash}`);const [us,ps,is]=await Promise.all([waitFor(get(uref)),waitFor(get(pref)),waitFor(get(iref))]);const old=us.exists()?us.val():{};const name=safeText(user.displayName,40)||safeText(old.displayName,40)||email.split('@')[0]||'Pengguna';const now=Date.now();const updates={};if(!us.exists())updates[`users/${user.uid}`]={displayName:name,createdAt:now,updatedAt:now};else if(old.displayName!==name)updates[`users/${user.uid}/displayName`]=name;updates[`users/${user.uid}/updatedAt`]=now;if(!ps.exists()||ps.val()?.displayName!==name)updates[`publicProfiles/${user.uid}`]={displayName:name,updatedAt:now};if(!is.exists())updates[`emailIndex/${hash}`]=user.uid;if(Object.keys(updates).length)await waitFor(update(ref(db),updates));myProfile={...(us.exists()?old:{}),displayName:name,updatedAt:now,createdAt:old.createdAt||now};renderMe()}
async function sendVerification(){if(!currentUser)return;const remain=verifyCooldownUntil-Date.now();if(remain>0){notice($('verifyNotice'),`Tunggu ${Math.ceil(remain/1000)} detik sebelum mengirim ulang.`);return}try{await sendEmailVerification(currentUser,actionCodeSettings());verifyCooldownUntil=Date.now()+60000;notice($('verifyNotice'),'Email verifikasi dikirim. Periksa Inbox, Spam, Promosi, atau Updates.')}catch(e){console.error(e);notice($('verifyNotice'),firebaseMessage(e),'error')}}
function closeMenu(){const m=$('accountMenu');m.classList.add('hidden');m.setAttribute('aria-hidden','true')}
function toggleMenu(){const m=$('accountMenu'),hidden=m.classList.toggle('hidden');m.setAttribute('aria-hidden',String(hidden));renderMe()}
function renderContacts(){const term=normalizeEmail($('contactSearch').value);const list=$('contactList');list.innerHTML='';const arr=Object.entries(contacts).map(([uid,v])=>({uid,...v})).filter(c=>!term||normalizeEmail(c.email).includes(term)||String(c.displayName||'').toLowerCase().includes(term));$('emptyContacts').classList.toggle('hidden',arr.length>0);for(const c of arr){const b=document.createElement('button');b.className=`contact-item ${c.uid===activeUid?'active':''}`;b.type='button';const img=document.createElement('img');img.src='img/chat_logo.png';img.alt='';const copy=document.createElement('div');copy.className='contact-copy';const strong=document.createElement('strong');strong.textContent=c.displayName||'Pengguna';const span=document.createElement('span');span.textContent=c.email||'Kontak';copy.append(strong,span);b.append(img,copy);b.addEventListener('click',()=>openConversation(c.uid));list.appendChild(b)}}
function listenContacts(){if(contactsUnsub)off(ref(db,`contacts/${currentUser.uid}`));const r=ref(db,`contacts/${currentUser.uid}`);contactsUnsub=onValue(r,snap=>{contacts=snap.exists()?snap.val():{};renderContacts()},err=>{console.error('contacts',err);toast('Kontak belum dapat dimuat.')})}
async function ensureChat(peerUid){const id=chatIdFor(currentUser.uid,peerUid),r=ref(db,`chats/${id}`),snap=await get(r);if(snap.exists())return id;const now=Date.now();await set(r,{type:'direct',createdAt:now,participants:{[currentUser.uid]:true,[peerUid]:true}});return id}

// Perbaikan 1: Penambahan goOnline(db) sebelum eksekusi pencarian
async function addContactByEmail(value){
    goOnline(db);
    await refreshUser(true);
    const email=normalizeEmail(value);
    if(!isEmail(email))throw new Error('Masukkan email yang valid.');
    if(email===normalizeEmail(currentUser.email))throw new Error('Anda tidak dapat menambahkan diri sendiri.');
    const hash=await sha256Hex(email);
    const idx=await waitFor(get(ref(db,`emailIndex/${hash}`)));
    if(!idx.exists())throw new Error('Kontak tidak ditemukan. Pastikan akun sudah verifikasi email dan login minimal sekali.');
    const uid=String(idx.val());
    if(!uid||uid===currentUser.uid)throw new Error('Kontak tidak valid.');
    const p=await waitFor(get(ref(db,`publicProfiles/${uid}`)));
    if(!p.exists())throw new Error('Profil kontak belum siap. Minta pengguna tersebut login kembali.');
    const data={displayName:safeText(p.val()?.displayName,40)||'Pengguna',email,addedAt:Date.now()};
    await waitFor(set(ref(db,`contacts/${currentUser.uid}/${uid}`),data));
    await ensureChat(uid);
    return{uid,...data}
}

async function openConversation(uid){const contact=contacts[uid];if(!contact)return;activeUid=uid;activeChatId=chatIdFor(currentUser.uid,uid);$('peerName').textContent=contact.displayName||'Pengguna';$('peerStatus').textContent=contact.email||'Email terverifikasi';$('welcomeConversation').classList.add('hidden');$('activeConversation').classList.remove('hidden');views.chat.classList.add('mobile-open');renderContacts();listenMessages()}
function listenMessages(){if(messagesUnsub)off(ref(db,`chats/${activeChatId}/messages`));const r=ref(db,`chats/${activeChatId}/messages`);messagesUnsub=onValue(r,snap=>{const list=$('messageList');list.innerHTML='';const data=snap.exists()?snap.val():{};const msgs=Object.entries(data).map(([id,m])=>({id,...m})).sort((a,b)=>(a.createdAt||0)-(b.createdAt||0));for(const m of msgs){const row=document.createElement('div');row.className=`message-row ${m.senderId===currentUser.uid?'mine':''}`;const bubble=document.createElement('div');bubble.className='message-bubble';const text=document.createElement('div');text.className='message-text';text.textContent=m.text||'';const meta=document.createElement('div');meta.className='message-meta';meta.textContent=formatTime(m.createdAt);bubble.append(text,meta);row.appendChild(bubble);list.appendChild(row)}requestAnimationFrame(()=>list.scrollTop=list.scrollHeight)},err=>{console.error('messages',err);toast('Pesan tidak dapat dimuat.')})}
async function sendMessage(){const input=$('messageInput'),text=safeText(input.value,4000);if(!text||!activeChatId||!currentUser)return;const old=input.value;input.value='';try{const r=push(ref(db,`chats/${activeChatId}/messages`));await waitFor(set(r,{senderId:currentUser.uid,text,createdAt:serverTimestamp()}))}catch(e){input.value=old;console.error(e);toast('Pesan gagal dikirim.')}}
function clearActive(){if(messagesUnsub)off(ref(db,`chats/${activeChatId}/messages`));messagesUnsub=null;activeUid=null;activeChatId=null;views.chat.classList.remove('mobile-open');$('activeConversation').classList.add('hidden');$('welcomeConversation').classList.remove('hidden');$('messageList').innerHTML='';renderContacts()}
function setPresence(online){if(!currentUser?.emailVerified)return;const r=ref(db,`presence/${currentUser.uid}`);if(online){set(r,{online:true,lastSeen:serverTimestamp()}).catch(()=>{});presenceDisconnect?.cancel?.();presenceDisconnect=onDisconnect(r);presenceDisconnect.set({online:false,lastSeen:serverTimestamp()}).catch(()=>{})}else{set(r,{online:false,lastSeen:serverTimestamp()}).catch(()=>{})}}
function cleanup(){if(contactsUnsub)off(ref(db,`contacts/${currentUser?.uid}`));if(messagesUnsub&&activeChatId)off(ref(db,`chats/${activeChatId}/messages`));contactsUnsub=null;messagesUnsub=null;presenceDisconnect?.cancel?.();presenceDisconnect=null}
async function initializeChat(user){if(!user.emailVerified)throw new Error('Email belum terverifikasi.');await ensureProfile(user);setView('chat');listenContacts();setPresence(true)}
async function logout(){closeMenu();setPresence(false);cleanup();try{await signOut(auth)}catch(e){console.error(e);toast('Gagal keluar. Coba lagi.')}}

$('loginForm').addEventListener('submit',async e=>{e.preventDefault();if(authBusy)return;const email=normalizeEmail($('loginEmail').value),pass=$('loginPassword').value;if(!isEmail(email)||!pass){notice($('authNotice'),'Email dan password wajib diisi dengan benar.','error');return}await persistenceReady.catch(()=>{});authBusy=true;const b=e.submitter;b.disabled=true;b.textContent='Memeriksa…';clearNotice($('authNotice'));try{const cred=await waitFor(signInWithEmailAndPassword(auth,email,pass),15000);currentUser=cred.user;await refreshUser(false);if(!currentUser.emailVerified){$('verifyAddress').textContent=currentUser.email;setView('verify');notice($('verifyNotice'),'Login berhasil. Selesaikan verifikasi email terlebih dahulu.','error');return}await waitFor(initializeChat(currentUser),15000);$('loginForm').reset()}catch(err){console.error('LOGIN',err);notice($('authNotice'),firebaseMessage(err),'error')}finally{authBusy=false;b.disabled=false;b.textContent='Masuk'}});
$('registerForm').addEventListener('submit',async e=>{e.preventDefault();if(authBusy)return;const name=safeText($('registerName').value,40),email=normalizeEmail($('registerEmail').value),p1=$('registerPassword').value,p2=$('registerPassword2').value;if(!name||!isEmail(email))return notice($('authNotice'),'Nama dan email wajib diisi.','error');if(!isStrongPassword(p1))return notice($('authNotice'),'Password harus 8–72 karakter dan memiliki huruf besar, kecil, angka, serta simbol.','error');if(p1!==p2)return notice($('authNotice'),'Konfirmasi password tidak sama.','error');await persistenceReady.catch(()=>{});authBusy=true;const b=e.submitter;b.disabled=true;b.textContent='Membuat…';try{const cred=await createUserWithEmailAndPassword(auth,email,p1);await updateProfile(cred.user,{displayName:name});currentUser=cred.user;await sendEmailVerification(currentUser,actionCodeSettings());$('registerForm').reset();$('verifyAddress').textContent=email;setView('verify');notice($('verifyNotice'),'Akun dibuat. Silakan verifikasi email Anda.')}catch(err){console.error('REGISTER',err);notice($('authNotice'),firebaseMessage(err),'error')}finally{authBusy=false;b.disabled=false;b.textContent='Daftar'}});
$('resetForm').addEventListener('submit',async e=>{e.preventDefault();const email=normalizeEmail($('resetEmail').value);if(!isEmail(email))return notice($('authNotice'),'Masukkan email yang valid.','error');const b=e.submitter;b.disabled=true;b.textContent='Mengirim…';try{await sendPasswordResetEmail(auth,email,actionCodeSettings());notice($('authNotice'),'Tautan reset dikirim jika akun tersedia.');$('resetForm').reset()}catch(err){console.error(err);notice($('authNotice'),firebaseMessage(err),'error')}finally{b.disabled=false;b.textContent='Kirim tautan'}});
$('showRegister').addEventListener('click',()=>switchAuth('register'));$('showLogin').addEventListener('click',()=>switchAuth('login'));$('showReset').addEventListener('click',()=>switchAuth('reset'));$('backToLogin').addEventListener('click',()=>switchAuth('login'));
$('resendVerification').addEventListener('click',sendVerification);$('verifyLogout').addEventListener('click',logout);$('checkVerification').addEventListener('click',async()=>{try{await refreshUser(false);if(!currentUser.emailVerified){notice($('verifyNotice'),'Belum terverifikasi. Buka email dan klik tautannya.','error');return}await initializeChat(currentUser)}catch(e){console.error(e);notice($('verifyNotice'),firebaseMessage(e),'error')}});
onAuthStateChanged(auth,async user=>{await persistenceReady.catch(()=>{});currentUser=user;if(!user){cleanup();myProfile=null;contacts={};clearActive();setView('auth');switchAuth('login');return}try{await refreshUser(false);if(!currentUser.emailVerified){$('verifyAddress').textContent=currentUser.email||'';setView('verify');return}await initializeChat(currentUser)}catch(e){console.error('AUTH INIT',e);cleanup();setView('auth');switchAuth('login');notice($('authNotice'),e?.message||firebaseMessage(e),'error')}});

$('accountButton').addEventListener('click',e=>{e.stopPropagation();toggleMenu()});$('accountMenu').addEventListener('click',e=>e.stopPropagation());document.addEventListener('click',closeMenu);$('menuLogout').addEventListener('click',logout);$('logoutButton')?.addEventListener('click',logout);$('menuTheme').addEventListener('click',()=>{document.body.classList.toggle('light');localStorage.setItem('arinex-theme',document.body.classList.contains('light')?'light':'dark');closeMenu()});
$('newChatButton').addEventListener('click',()=>{$('modalBackdrop').classList.remove('hidden');$('contactEmail').value='';clearNotice($('contactModalNotice'));setTimeout(()=>$('contactEmail').focus(),30)});$('addContactButton').addEventListener('click',()=>$('newChatButton').click());$('emptyAddButton').addEventListener('click',()=>$('newChatButton').click());$('closeContactModal').addEventListener('click',()=>$('modalBackdrop').classList.add('hidden'));$('modalBackdrop').addEventListener('click',e=>{if(e.target===$('modalBackdrop'))$('modalBackdrop').classList.add('hidden')});
$('contactForm').addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;b.textContent='Mencari…';try{const r=await addContactByEmail($('contactEmail').value);$('modalBackdrop').classList.add('hidden');toast(`${r.displayName} ditambahkan.`);await openConversation(r.uid)}catch(err){console.error('CONTACT',err);notice($('contactModalNotice'),err?.message||firebaseMessage(err),'error')}finally{b.disabled=false;b.textContent='Cari & tambah'}});$('contactSearch').addEventListener('input',renderContacts);$('messageForm').addEventListener('submit',e=>{e.preventDefault();sendMessage()});$('backToContacts').addEventListener('click',clearActive);$('emojiButton').addEventListener('click',()=>{$('messageInput').value+='🙂';$('messageInput').focus()});$('chatMenuButton').addEventListener('click',()=>toast('Percakapan realtime aktif'));
document.querySelectorAll('.eye').forEach(btn=>btn.addEventListener('click',()=>{const i=$(btn.dataset.target);i.type=i.type==='password'?'text':'password'}));
if(localStorage.getItem('arinex-theme')==='light')document.body.classList.add('light');
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;$('installButton').classList.remove('hidden');$('menuInstall').classList.remove('hidden')});async function install(){if(!deferredInstallPrompt)return;deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;$('installButton').classList.add('hidden');$('menuInstall').classList.add('hidden')}$('installButton').addEventListener('click',install);$('menuInstall').addEventListener('click',()=>{closeMenu();install()});
document.addEventListener('visibilitychange',()=>setPresence(document.visibilityState==='visible'));window.addEventListener('beforeunload',()=>setPresence(false));
document.addEventListener('contextmenu',e=>{if(!e.target.closest('input,textarea'))e.preventDefault()});document.addEventListener('selectstart',e=>{if(!e.target.closest('input,textarea,[contenteditable="true"]'))e.preventDefault()});document.addEventListener('dragstart',e=>e.preventDefault());document.addEventListener('keydown',e=>{const editable=e.target.closest('input,textarea,[contenteditable="true"]');if(!editable&&(e.ctrlKey||e.metaKey)&&['c','x','a','u','s','p'].includes(e.key.toLowerCase())){e.preventDefault()}});

// Perbaikan 2: Unregister Service Worker lama secara paksa
if ('serviceWorker' in navigator) {
    navigator.serviceWorker.getRegistrations().then((registrations) => {
        for (let reg of registrations) {
            reg.unregister();
            console.log('Service Worker lama berhasil dihapus dari sistem');
        }
    });
}
